// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiuuWv5R7sW92iBPoxRHIESlfFn93-Ku0',
    appId: '1:267799005741:web:4a267f40c1a221e2b146a4',
    messagingSenderId: '267799005741',
    projectId: 'fooddelivery24-a9fbb',
    authDomain: 'fooddelivery24-a9fbb.firebaseapp.com',
    storageBucket: 'fooddelivery24-a9fbb.firebasestorage.app',
    measurementId: 'G-73NKXYS3Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpFWrbgKvaiJAvWHJNpj7fcnl4p0-WIyc',
    appId: '1:267799005741:android:c1199431bca29d87b146a4',
    messagingSenderId: '267799005741',
    projectId: 'fooddelivery24-a9fbb',
    storageBucket: 'fooddelivery24-a9fbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWC13u7wBBkUechJ-NkB3XqC0bl1p1JaI',
    appId: '1:267799005741:ios:88d7826daad76398b146a4',
    messagingSenderId: '267799005741',
    projectId: 'fooddelivery24-a9fbb',
    storageBucket: 'fooddelivery24-a9fbb.firebasestorage.app',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWC13u7wBBkUechJ-NkB3XqC0bl1p1JaI',
    appId: '1:267799005741:ios:88d7826daad76398b146a4',
    messagingSenderId: '267799005741',
    projectId: 'fooddelivery24-a9fbb',
    storageBucket: 'fooddelivery24-a9fbb.firebasestorage.app',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiuuWv5R7sW92iBPoxRHIESlfFn93-Ku0',
    appId: '1:267799005741:web:9b1549c0c3a87fb5b146a4',
    messagingSenderId: '267799005741',
    projectId: 'fooddelivery24-a9fbb',
    authDomain: 'fooddelivery24-a9fbb.firebaseapp.com',
    storageBucket: 'fooddelivery24-a9fbb.firebasestorage.app',
    measurementId: 'G-D7TB3DW1NM',
  );
}
